---

- name: Install Homebrew
  action: "shell ruby -e '$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)' creates=/usr/local/bin/brew"
  register: brew_install

# - name: Update Homebrew
# when: brew_install is defined
# action: homebrew update_homebrew=yes name=*

- name: Install brews
  action: homebrew state=installed
    name='zsh,zsh-completions,git,vim,curl,wget,tmux,jq'
  register: install_brews

- name: Change shell to zsh
  action: command chsh -s /usr/local/bin/zsh
  failed_when: false

# Grab ZSH configs
- name: Grab dot files
  action: get_url url={{ item.url }} dest={{ item.dest }}
  with_items:
  - { url: 'https://raw.githubusercontent.com/joethemongoose/Dotfiles/master/zfunctions',   dest: '~/.zfunctions' }
  - { url: 'https://raw.githubusercontent.com/joethemongoose/Dotfiles/master/zlogin-osx',   dest: '~/.zlogin' }
  - { url: 'https://raw.githubusercontent.com/joethemongoose/Dotfiles/master/zprofile-osx', dest: '~/.zprofile' }
  - { url: 'https://raw.githubusercontent.com/joethemongoose/Dotfiles/master/zshenv-osx',   dest: '~/.zshenv' }
  - { url: 'https://raw.githubusercontent.com/joethemongoose/Dotfiles/master/zshrc-osx',    dest: '~/.zshrc' }
  - { url: 'https://raw.githubusercontent.com/joethemongoose/Dotfiles/master/zshrc.zni',    dest: '~/.zsh.zni' }
  - { url: 'https://raw.githubusercontent.com/joethemongoose/Dotfiles/master/tmux.conf',    dest: '~/.tmux.conf' }
  - { url: 'https://raw.githubusercontent.com/joethemongoose/Dotfiles/master/.vimrc.after', dest: '~/.vimrc.after' }

# install antigen
- name: get antigen
  action: git repo=https://github.com/zsh-users/antigen.git dest=~/.antigen update=yes

# install janus
- name: install janus
  action: "shell $(curl -Lo- https://bit.ly/janus-bootstrap | bash) creates=~/.vim"
  register: janus_install

- name: update janus
  when: janus_install.changed is not defined
  action: shell chdir=~/.vim rake && rake

# RVM
- name: Install RVM
  action: "shell creates=~/.rvm $(curl -sSL https://get.rvm.io | bash -s stable --ruby --with-gems='bundler' --autolibs=3)"
  register: rvm_install

- name: Update RVM
  when: rvm_install.changed is not defined
  action: "shell rvm get stable"

# NVM
- name: install nvm
  action: git repo=https://github.com/creationix/nvm.git dest=~/.nvm update=yes

# GVM
- name: install gvm
  action: "shell $(curl -sSL https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer | bash ) create=~/.gvm"
